AllCops:
  Exclude:
    - vendor/**
    - metadata.rb
    - '**/Puppetfile'
    - Puppetfile


Documentation:
  Enabled: false
AlignParameters:
  Enabled: true
Encoding:
  Enabled: true
HashSyntax:
  Enabled: true
LineLength:
  Enabled: false
MethodLength:
  Max: 30
NumericLiterals:
  MinDigits: 10
