---
AllCops:
  Exclude:
  - vendor/**/*
Style/Encoding:
  Enabled: false
Documentation:
  Enabled: false
AlignParameters:
  Enabled: true
HashSyntax:
  Enabled: true
LineLength:
  Enabled: false
EmptyLinesAroundBlockBody:
  Enabled: false
MethodLength:
  Max: 40
NumericLiterals:
  MinDigits: 10
Metrics/BlockLength:
  Max: 42
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 30
